# Generated by Django 3.1.1 on 2020-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('time', models.DateTimeField()),
                ('author', models.CharField(max_length=30)),
                ('publish_id', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=3000)),
            ],
        ),
    ]
