# Generated by Django 3.1.1 on 2020-10-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboHot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('hot', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='publish_id',
        ),
        migrations.AddField(
            model_name='articles',
            name='cluster_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
