# Generated by Django 3.1.1 on 2020-10-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201013_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
