# Generated by Django 3.1.1 on 2020-10-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201013_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibohot',
            name='url',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
