# Generated by Django 3.1.1 on 2020-10-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201016_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibohot',
            old_name='url',
            new_name='urls',
        ),
    ]
