# Generated by Django 3.1.1 on 2020-10-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20201016_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibohot',
            name='urls',
        ),
        migrations.AddField(
            model_name='weibohot',
            name='url0',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
