# Generated by Django 3.1.1 on 2020-10-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_weibohot_url0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibohot',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
