# Generated by Django 3.1.1 on 2020-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20201016_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
