# Generated by Django 3.1.1 on 2020-10-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201022_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='emotion',
            field=models.FloatField(default=0.0),
        ),
    ]
