# Generated by Django 3.1.2 on 2020-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_articles_emotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboSocialEvents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
