# Generated by Django 3.1.2 on 2020-11-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_weibosocialevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='similar_docs',
            field=models.CharField(default='', max_length=200),
        ),
    ]
