# Generated by Django 3.1.2 on 2020-11-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_articles_similar_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='similar_docs',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
