# Generated by Django 3.1.1 on 2020-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatmapdata',
            name='data',
        ),
        migrations.RemoveField(
            model_name='heatmapdata',
            name='date',
        ),
        migrations.AddField(
            model_name='heatmapdata',
            name='locdict',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='heatmapdata',
            name='time',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
