# Generated by Django 2.2.4 on 2019-08-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='The date for meeting')),
                ('start_time', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=100)),
                ('teams', models.CharField(max_length=255)),
            ],
        ),
    ]
